import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  // ========== General Styles (PRESERVED) ==========
  container: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "#f0f4ff",
    paddingTop: 80,
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 30,
    fontFamily: "Righteous",
    fontWeight: "bold",
    color: "#4F74B8",
    marginBottom: 40,
  },
  subtitle: {
    fontSize: 20,
    fontFamily: "Righteous",
    color: "#333333",
    marginTop: 5,
    marginBottom: 20,
    textAlign: "center",
  },
  input: {
    width: "100%",
    height: 50, // Added height for consistency
    padding: 15,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    marginBottom: 15,
    backgroundColor: "#fff",
    fontSize: 16,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    height: 50,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    backgroundColor: "#fff",
    paddingHorizontal: 15,
    marginBottom: 15,
  },
  // ===== Style for TextInput Field in Signup Login ======
  inputField: {
    flex: 1,
    fontSize: 16,
    height: "100%",
  },
  icon: {
    marginLeft: 10,
  },
  button: {
    backgroundColor: "#a6c8ff",
    padding: 15,
    borderRadius: 10,
    width: "100%",
    alignItems: "center",
    marginVertical: 10,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
  },
  linkText: {
    color: "#4F74B8",
    fontWeight: "bold",
  },

  // ========== Logo, Splash, Logout Styles (PRESERVED) ==========
  logo: { width: 500, height: 500 },
  welcomeLogo: { width: 412, height: 371, marginBottom: -80, marginTop: -30 },
  splashContainer: {
    flex: 1,
    backgroundColor: "#BED5EA",
    justifyContent: "center",
    alignItems: "center",
  },
  logoutButton: {
    backgroundColor: "#ff7675",
    padding: 15,
    borderRadius: 10,
    width: 200,
    alignItems: "center",
    marginVertical: 10,
  },

  // ========== Styles for StudentHomeScreen (UPDATED & FIXED) ==========
  backgroundImage: { flex: 1, width: "100%", height: "100%" },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(240, 244, 255, 0.85)",
  },
  studentScreenContainer: {
    flex: 1,
    backgroundColor: "transparent", // <-- Change this to transparent
  },
  studentScrollContainer: {
    paddingHorizontal: 15,
    paddingTop: 50,
    paddingBottom: 100,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  appTitle: {
    fontSize: 24,
    fontFamily: "Righteous",
    color: "#4F74B8",
  },
  notificationIcon: { width: 30, height: 30 },
  profileCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 12,
    marginVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  profileImage: { width: 60, height: 60, borderRadius: 30 },
  profileInfo: { flex: 1, marginLeft: 15 },
  rank: { fontSize: 16, fontWeight: "bold", color: "#4F74B8" },
  rankNote: { fontSize: 12, color: "gray", fontStyle: "italic" },
  username: { fontSize: 18, fontWeight: "600", color: "#333" },
  menuIcon: { width: 24, height: 24 },
  progressWrapper: {
    height: 8,
    backgroundColor: "#e0e7ff",
    borderRadius: 4,
    marginTop: 15,
    overflow: "hidden",
  },
  progressTrack: {
    height: "100%",
    backgroundColor: "#d1d9f0",
  },
  progressFill: {
    height: "100%",
    width: "25%",
    backgroundColor: "#4F74B8",
    borderRadius: 4,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginTop: 25,
    marginBottom: 10,
    textAlign: "center",
  },
  questCard: {
    backgroundColor: "rgba(255, 255, 255, 0.7)", // <-- 90% opaque white
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
  },
  questCategory: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#4F74B8",
    marginTop: 10,
    marginBottom: 5,
  },
  questItem: {
    fontSize: 15,
    color: "#555",
    paddingVertical: 5,
  },
  placeholder: {
    height: 30,
    backgroundColor: "#f0f4ff",
    borderRadius: 8,
    marginVertical: 5,
  },
  scoreContainer: {
    position: "absolute",
    bottom: 85,
    left: 15,
    right: 15,
    zIndex: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  scoreText: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#333",
  },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    height: 85,
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderTopColor: "#e0e0e0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 5,
  },
  navIconContainer: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  navIcon: {
    width: 28,
    height: 28,
  },

  // ========== Styles for AdminHomeScreen (FINAL) ==========
  adminScrollContainer: {
    paddingHorizontal: 15,
    paddingBottom: 30,
  },
  adminScreenContainer: {
    flex: 1,
    backgroundColor: "#f0f4ff",
  },
  adminHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 10,
  },
  adminAppTitle: {
    fontSize: 24,
    fontFamily: "Righteous",
    color: "#4F74B8",
  },
  adminNotificationIcon: {
    width: 30,
    height: 30,
  },
  adminProfileCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 15,
    marginHorizontal: 15,
    marginVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  adminProfileImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: "#f0f4ff",
  },
  adminProfileInfo: {
    flex: 1,
    marginLeft: 15,
  },
  adminRank: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#4F74B8",
  },
  adminUsername: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
  },
  adminMenuIcon: {
    width: 24,
    height: 24,
  },
  adminWelcomeText: {
    fontSize: 16,
    color: "#333",
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  adminContentContainer: {
    paddingHorizontal: 15,
  },
  adminSearchRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  adminSearchWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 45,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  adminSearchIcon: {
    width: 20,
    height: 20,
    marginRight: 8,
    tintColor: "#888",
  },
  adminSearchInput: {
    flex: 1,
    fontSize: 16,
    color: "#000",
  },
  adminActionIconBtn: {
    marginLeft: 10,
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    justifyContent: "center",
    alignItems: "center",
    height: 45,
    width: 45,
  },
  adminActionIcon: {
    width: 24,
    height: 24,
  },
  adminTabContainer: {
    flexDirection: "row",
    marginBottom: 15,
  },
  adminTab: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginRight: 10,
    backgroundColor: "#e9eef7",
  },
  adminTabActive: {
    backgroundColor: "#4F74B8",
  },
  adminTabIcon: {
    width: 16,
    height: 16,
    marginRight: 8,
    tintColor: "#fff",
  },
  adminTabText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
  },
  adminCard: {
    backgroundColor: "#ffffff",
    borderRadius: 15,
    padding: 15,
    marginBottom: 15,
  },
  adminCardTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 15,
  },
  adminQuestBarContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
    height: 100,
  },
  adminQuestBarWrapper: {
    flex: 1,
    marginHorizontal: 5,
    height: "100%",
    backgroundColor: "#f0f4ff",
    borderRadius: 8,
    justifyContent: "flex-end",
  },
  adminQuestBar: {
    width: "100%",
    borderRadius: 8,
  },
  adminClassCirclesRow: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  adminCircleContainer: {
    alignItems: "center",
  },
  adminCircleLabel: {
    marginTop: 8,
    fontSize: 12,
    color: "#333333",
  },
  adminCalendar: {
    borderRadius: 15,
  },
  adminMenuOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    zIndex: 1000,
  },
  adminMenuContainer: {
    position: "absolute",
    top: 100,
    right: 20,
    backgroundColor: "white",
    borderRadius: 8,
    width: 260,
    padding: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  adminMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 15,
  },
  adminMenuItemIcon: {
    fontSize: 18,
    marginRight: 15,
  },
  adminMenuItemText: {
    fontSize: 16,
    color: "#333",
    fontWeight: "500",
  },
  adminMenuSeparator: {
    height: 1,
    backgroundColor: "#e0e0e0",
    marginVertical: 4,
  },

  // ========== CREATE TASK SCREEN STYLES (PRESERVED) ==========
  createTaskContainer: {
    flex: 1,
    backgroundColor: "#eef2f9",
    paddingTop: 10,
  },
  taskCard: {
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 20,
    marginHorizontal: 15,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  taskSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    paddingBottom: 10,
  },
  taskSectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  taskSectionIcon: {
    fontSize: 24,
    color: "#4F74B8",
  },
  taskItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  taskText: {
    flex: 1,
    marginRight: 10,
    fontSize: 16,
    color: "#555",
  },
  taskIcon: {
    fontSize: 20,
    marginLeft: 15,
  },
  addMoreText: {
    fontSize: 16,
    color: "#4F74B8",
    textAlign: "center",
    marginTop: 15,
  },
  formRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  inputGroup: {
    flex: 1,
    marginBottom: 15,
    marginHorizontal: 5,
  },
  inputLabel: {
    fontSize: 14,
    color: "#777",
    marginBottom: 5,
  },
  textInput: {
    backgroundColor: "#f0f4ff",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
  },
  actionButtonsContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginHorizontal: 15,
    marginBottom: 40,
  },
  actionButton: {
    backgroundColor: "#4F74B8",
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
    marginLeft: 10,
  },
  actionButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  cancelButton: {
    backgroundColor: "#dcdcdc",
  },
  cancelButtonText: {
    color: "#333",
  },
  addTaskContainer: {
    flexDirection: "row",
    marginBottom: 15,
  },
  addTaskInput: {
    flex: 1,
    backgroundColor: "#f0f4ff",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    marginRight: 10,
  },
  addTaskButton: {
    backgroundColor: "#4F74B8",
    borderRadius: 8,
    justifyContent: "center",
    paddingHorizontal: 15,
  },
  addTaskButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  taskEditTextInput: {
    flex: 1,
    borderBottomWidth: 1,
    borderColor: "#4F74B8",
    fontSize: 16,
    color: "#333",
  },
  pointsButton: {
    backgroundColor: "#e0e0e0",
    borderRadius: 5,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginHorizontal: 4,
  },
  pointsButtonActive: {
    backgroundColor: "#4F74B8",
  },
  pointsButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  pointsInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f0f4ff",
    borderRadius: 5,
    paddingHorizontal: 6,
    marginRight: 8,
  },
  pointsInput: {
    width: 40,
    paddingVertical: 4,
    textAlign: "right",
    fontSize: 14,
    fontWeight: "bold",
    color: "#4F74B8",
  },
  pointsInputLabel: {
    fontSize: 14,
    color: "#777",
    marginLeft: 2,
  },

  myClassContainer: {
    flex: 1,
    backgroundColor: "#f0f4ff",
  },
  myClassTitle: {
    fontSize: 26,
    fontFamily: "Righteous",
    color: "#4F74B8",
    textAlign: "center",
    marginVertical: 20,
  },
  myClassCard: {
    backgroundColor: "#ffffff",
    borderRadius: 15,
    padding: 20,
    marginHorizontal: 15,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  myClassSectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    paddingBottom: 10,
  },
  myClassInput: {
    width: "100%",
    backgroundColor: "#f9f9f9",
    borderRadius: 10,
    padding: 15,
    fontSize: 16,
    marginBottom: 10,
    borderColor: "#e0e7ff",
    borderWidth: 1,
  },
  myClassButton: {
    backgroundColor: "#4F74B8",
    paddingVertical: 15,
    borderRadius: 10,
    alignItems: "center",
  },
  myClassButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  myClassListItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  myClassAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 15,
    borderWidth: 1,
    borderColor: "#e0e7ff",
  },
  myClassUserInfo: {
    flex: 1,
  },
  myClassUsername: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  myClassLrn: {
    fontSize: 14,
    color: "gray",
    fontStyle: "italic",
  },
  myClassActionButtons: {
    flexDirection: "row",
    alignItems: "center",
  },
  myClassAcceptButton: {
    backgroundColor: "#27ae60",
    marginRight: 8,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  myClassDeclineButton: {
    backgroundColor: "#c0392b",
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  myClassEmptyText: {
    textAlign: "center",
    color: "gray",
    marginVertical: 15,
    fontSize: 15,
    lineHeight: 22,
  },

  // ========== PROFILE EDIT SCREEN (PRESERVED) ==========
  ProfileEditScreencontainer: {
    flex: 1,
    alignItems: "center",
    padding: 20,
    backgroundColor: "#f0f4ff",
  },
  ProfileEditScreenImage: {
    width: 150,
    height: 150,
    borderRadius: 75,
    marginBottom: 10,
  },
  changeText: {
    textAlign: "center",
    color: "#4F74B8",
    marginBottom: 20,
  },
  ProfileEditScreeninput: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 10,
    borderRadius: 5,
    marginBottom: 20,
    backgroundColor: "#fff",
  },
  ProfileEditScreenbutton: {
    backgroundColor: "#4F74B8",
    padding: 15,
    borderRadius: 5,
    width: "100%",
    alignItems: "center",
  },
  ProfileEditScreenbuttonText: {
    color: "#fff",
    fontWeight: "bold",
  },

  // ========== LEADERBOARDS SCREEN STYLES (CLEANED UP) ==========
  leaderboardContainer: {
    flex: 1,
    backgroundColor: "#f0f4ff",
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  leaderboardTabRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e0e7ff",
    borderRadius: 20,
    padding: 4,
    marginBottom: 20,
  },
  leaderboardTab: {
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 18,
  },
  leaderboardTabActive: {
    backgroundColor: "#4F74B8",
  },
  leaderboardTabText: {
    fontWeight: "bold",
    color: "#4F74B8",
  },
  leaderboardTabTextActive: {
    color: "#fff",
  },
  podiumCard: {
    backgroundColor: "#4F74B8",
    borderRadius: 20,
    padding: 15,
    paddingTop: 30,
    marginBottom: 20,
  },
  podiumContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
    height: 150,
  },
  podiumItem: {
    alignItems: "center",
    width: "30%",
  },
  podiumItem1: {
    transform: [{ translateY: -25 }],
  },
  podiumAvatar1: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 4,
    borderColor: "#FFD700",
  },
  podiumAvatar2: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 3,
    borderColor: "#C0C0C0",
  },
  podiumAvatar3: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 3,
    borderColor: "#CD7F32",
  },
  podiumName: {
    fontWeight: "bold",
    color: "#fff",
    marginTop: 8,
    fontSize: 16,
  },
  podiumScore: {
    color: "#e0e7ff",
    fontSize: 12,
  },
  crownIcon: {
    width: 40,
    height: 40,
    position: "absolute",
    top: -25,
    zIndex: 1,
  },
  timeTabRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  timeTab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
  },
  timeTabActive: {
    borderBottomWidth: 3,
    borderBottomColor: "#4F74B8",
  },
  timeTabText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "gray",
  },
  timeTabTextActive: {
    color: "#4F74B8",
  },
  rankListContainer: {
    marginBottom: 20,
  },
  rankListHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e7ff",
  },
  rankListHeaderText: {
    fontSize: 14,
    color: "gray",
    fontWeight: "bold",
  },
  rankItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  rankPosition: {
    width: 40,
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  rankStudentInfo: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  rankAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 15,
  },
  rankName: {
    fontSize: 16,
    fontWeight: "500",
    color: "#333",
  },
  rankScoreContainer: {
    backgroundColor: "#e0e7ff",
    borderRadius: 15,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  rankScoreText: {
    color: "#4F74B8",
    fontWeight: "bold",
  },
  scrollChevron: {
    width: 30,
    height: 30,
    resizeMode: "contain",
    alignSelf: "center",
    opacity: 0.5,
    marginBottom: 40,
  },

  // ========== MILESTONES SCREEN STYLES ==========
  milestonesContainer: {
    flex: 1,
    backgroundColor: "#f0f4ff", // Standard background color
  },
  milestonesGrid: {
    padding: 10,
  },
  milestoneCard: {
    flex: 1,
    margin: 10,
    backgroundColor: "#fff",
    borderRadius: 20,
    aspectRatio: 1, // This makes the card a perfect square
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    padding: 10,
  },
  milestoneIcon: {
    width: "70%",
    height: "70%",
    resizeMode: "contain",
    marginBottom: 5,
  },
  milestoneName: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
  },
  lockedMilestoneQuestionMark: {
    fontSize: 60,
    color: "#4F74B8",
    fontWeight: "bold",
  },
});

export default styles;
